"""empty message

Revision ID: 8dd61faecd24
Revises: 
Create Date: 2019-06-04 11:30:42.235997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd61faecd24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), nullable=True),
    sa.Column('password', sa.VARCHAR(length=90), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
